import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {calculators,categories} from '../src/catalog.mjs';
import {config} from '../src/config.mjs';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const root=new URL('../',import.meta.url);
const write=(path,content)=>writeFile(new URL(path,root),content.endsWith('\n')?content:content+'\n');
const url=path=>config.origin+config.base+path;
await mkdir(new URL('assets/tools/',root),{recursive:true});
await mkdir(new URL('docs/',root),{recursive:true});
const css=await readFile(new URL('../src/styles.css',import.meta.url),'utf8');
await write('styles.css',css);
await write('assets/core.mjs',await readFile(new URL('../src/core.mjs',import.meta.url),'utf8'));
await write('assets/app.mjs',await readFile(new URL('../src/app.mjs',import.meta.url),'utf8'));
await write('assets/integrations.mjs',await readFile(new URL('../src/integrations.mjs',import.meta.url),'utf8'));
await write('assets/config.mjs',`export const config = ${JSON.stringify(config)};`);
const nav=`<a class="skip" href="#main">Skip to content</a><header><nav aria-label="Main navigation"><a class="brand" href="${config.base}"><span class="brand-mark" aria-hidden="true">=</span>Calculator World</a><div class="nav-links"><a href="${config.base}#find">Find a calculator</a><a href="${config.base}#categories">Categories</a><a href="${config.base}about.html">About</a></div></nav></header>`;
const footer=`<footer><div><a class="brand" href="${config.base}">Calculator World</a><p>Useful answers for everyday questions.<br>Free to use. No account needed.</p></div><nav aria-label="Footer navigation"><a href="${config.base}about.html">About</a><a href="${config.base}privacy.html">Privacy</a><a href="${config.base}terms.html">Terms</a><a href="${config.base}contact.html">Contact</a></nav></footer>`;
function page(path,title,description,body,{calculator,crumbs=[],noindex=false}={}){
 const schema=crumbs.length?`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((c,i)=>({'@type':'ListItem',position:i+1,name:c[0],item:url(c[1])}))}).replaceAll('<','\\u003c')}</script>`:'';
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="google-site-verification" content="${escape(config.verification)}"><title>${escape(title)} | Calculator World</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${url(path)}">${noindex?'<meta name="robots" content="noindex">':''}<meta name="theme-color" content="#176451"><link rel="icon" href="${config.base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${config.base}styles.css">${schema}<script type="module" src="${config.base}assets/app.mjs"></script></head><body${calculator?` data-calculator="${calculator}"`:''}>${nav}<main id="main">${body}</main>${footer}</body></html>\n`;
}
const cards=list=>`<div class="cards">${list.map(c=>`<article class="card" data-search="${escape((c.title+' '+c.description+' '+categories[c.category][0]).toLowerCase())}"><p class="eyebrow">${escape(categories[c.category][0])}</p><h3><a href="${config.base+c.id}.html">${escape(c.title)}</a></h3><p>${escape(c.description)}</p><span class="card-arrow" aria-hidden="true">↗</span></article>`).join('')}</div>`;
const categoryPath=k=>`category-${k}.html`;
const search=`<div class="search-box"><label for="search">Search calculators</label><input id="search" type="search" autocomplete="off" placeholder="Try mortgage, paint or percentage"><p id="search-status" role="status" aria-live="polite">${calculators.length} calculators to explore</p></div>`;
const categoryLinks=Object.entries(categories).map(([k,[name]])=>`<a href="${config.base+categoryPath(k)}">${escape(name)} <span>${calculators.filter(c=>c.category===k).length}</span></a>`).join('');
await write('index.html',page('','Free Everyday Calculators',`Find the calculator you need: ${calculators.length} free tools for money, math, dates, home projects, conversions and everyday decisions.`,
 `<section class="hero"><p class="eyebrow">Simple tools. Clear answers.</p><h1>Find the calculator<br>you need.</h1><p class="lead">From the monthly payment to the last square metre.<br>Work it out with free tools that show the maths.</p></section><section id="find" aria-labelledby="find-title"><h2 id="find-title" class="sr-only">Find a calculator</h2>${search}</section><section id="categories"><h2>Browse by category</h2><div class="category-links">${categoryLinks}</div></section><section aria-labelledby="all-title"><div class="section-heading"><h2 id="all-title">All calculators</h2><span>${calculators.length} useful tools</span></div>${cards(calculators)}<p id="no-results" hidden>No calculators match that search. Try a shorter phrase or browse a category above.</p></section><section class="about-strip"><h2>An answer you can understand.</h2><p>Each calculator includes the formula, a worked example and its assumptions. Your inputs stay in your browser. Choose a tool, change the example values and see how the result changes.</p></section>`));
for(const [k,[name,description]] of Object.entries(categories)){
 const list=calculators.filter(c=>c.category===k);
 await write(categoryPath(k),page(categoryPath(k),name+' Calculators',description,`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${config.base}">Home</a><span aria-hidden="true">/</span><span>${name}</span></nav><p class="eyebrow">${list.length} free tools</p><h1>${name} calculators</h1><p class="lead">${description}</p>${cards(list)}<section><h2>More ways to work it out</h2><div class="category-links">${categoryLinks}</div></section>`,{crumbs:[['Home',''],[name,categoryPath(k)]]}));
}
function field(f){
 const id='field-'+f.key, common=`id="${id}" name="${f.key}" required aria-describedby="form-help"`;
 let control;
 if(f.type==='select')control=`<select ${common}>${f.options.map(([v,t])=>`<option value="${escape(v)}"${v===f.value?' selected':''}>${escape(t)}</option>`).join('')}</select>`;
 else if(f.type==='list')control=`<textarea ${common} rows="3">${escape(f.value)}</textarea>`;
 else control=`<input ${common} type="${f.type}" value="${escape(f.value)}"${f.type==='number'?` step="${f.integer?'1':'any'}"${f.min!==undefined?` min="${f.min}"`:''}${f.max!==undefined?` max="${f.max}"`:''} inputmode="decimal"`:f.type==='date'?' min="0001-01-01" max="9999-12-31"':''}>`;
 return `<div class="field"><label for="${id}">${escape(f.label)}</label>${control}</div>`;
}
const explicitRelated={
 'mortgage-calculator':['loan-calculator','car-loan-calculator','compound-interest-calculator'],
 'tile-calculator':['flooring-calculator','room-area-calculator','square-footage-calculator'],
 'fuel-cost-calculator':['fuel-efficiency-calculator','annual-fuel-cost-calculator','cost-per-kilometre-calculator'],
 'vat-calculator':['sales-tax-calculator','profit-margin-calculator','markup-calculator'],
 'bmi-calculator':['weight-converter','length-converter','running-pace-calculator']
};
for(const c of calculators){
 const peers=calculators.filter(x=>x.category===c.category&&x.id!==c.id);
 const index=calculators.filter(x=>x.category===c.category).findIndex(x=>x.id===c.id);
 let related=explicitRelated[c.id]?.map(id=>calculators.find(x=>x.id===id));
 if(!related)related=peers.length?[...peers.slice(index),...peers.slice(0,index)].slice(0,3):calculators.slice(0,3);
 const name=categories[c.category][0], path=c.id+'.html';
 const body=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${config.base}">Home</a><span aria-hidden="true">/</span><a href="${config.base+categoryPath(c.category)}">${escape(name)}</a><span aria-hidden="true">/</span><span>${escape(c.title)}</span></nav><p class="eyebrow">${escape(name)}</p><h1>${escape(c.title)}</h1><p class="lead">${escape(c.description)}</p><section class="tool" aria-label="Calculator"><form novalidate><p id="form-help" class="form-help">Example values are filled in. Replace them with your own; all fields are required.</p><div class="fields">${c.fields.map(field).join('')}</div><div class="actions"><button type="submit">Calculate</button><button type="reset" class="secondary">Reset example</button></div><p id="form-error" role="alert" hidden></p></form><div class="result" id="result" role="status" aria-live="polite" aria-atomic="true"><span class="eyebrow">Your result</span><p>Check the example values, then select Calculate.</p></div><noscript><p>JavaScript is required for the interactive calculation. The formula and worked example below remain available.</p></noscript></section><div data-ad-position="afterResult" hidden></div><div class="reading"><section><h2>How to use this calculator</h2><ol><li>Enter ${c.fields.map(f=>escape(f.label.toLowerCase())).join(', ')}.</li><li>Select Calculate to see the result. After your first calculation, results update as you edit.</li><li>Read the assumptions below to check that this model fits your question.</li></ol></section><section><h2>Formula and method</h2><p class="formula">${escape(c.formula)}</p><h2>Worked example</h2><p>${escape(c.example)}</p><h2>Assumptions and interpretation</h2><p>${escape(c.notes)}</p></section><div data-ad-position="afterExplanation" hidden></div><section><h2>Common question</h2><h3>${escape(c.faq[0])}</h3><p>${escape(c.faq[1])}</p></section>${c.sources?`<section><h2>Sources</h2><ul>${c.sources.map(([label,href])=>`<li><a href="${escape(href)}">${escape(label)}</a></li>`).join('')}</ul></section>`:''}</div><section><h2>Related calculators</h2>${cards(related)}</section>`;
 await write(path,page(path,c.title,c.description,body,{calculator:c.id,crumbs:[['Home',''],[name,categoryPath(c.category)],[c.title,path]]}));
 const serial=JSON.stringify({...c,solve:undefined});
 await write('assets/tools/'+c.id+'.mjs',`import {assert,payment,future,date,iso,days,gcd,payoff} from '../core.mjs';\n${c.units?`const units=${JSON.stringify(c.units)};\n`:''}export default {...${serial},solve: ${c.solve.toString()}};`);
}
const info={
 'about':['About Calculator World','Learn how Calculator World builds and checks free, transparent browser-based calculators.',`<p>Calculator World is an independent collection of practical tools for everyday questions. It is maintained through the <a href="https://github.com/Colonel94/calculator-world">Colonel94/calculator-world repository</a>.</p><h2>How the tools are made</h2><p>Each tool has a stated formula, example and limitations. Shared validation checks required fields and numeric ranges. Automated tests cover reference examples, edge cases and generated links. Calculations run locally in your browser without an account.</p><h2>Corrections and transparency</h2><p>These tools can still contain mistakes or assumptions that do not fit your situation. Use the <a href="contact.html">contact page</a> to report a reproducible problem. Significant decisions deserve independent verification.</p><h2>How the site is supported</h2><p>The tools are free. There are currently no active ads or analytics trackers. Advertising may be introduced later, with privacy disclosures updated before activation.</p>`],
 'privacy':['Privacy Policy','How Calculator World handles calculator inputs, hosting information and potential future advertising.',`<p>Last updated: September 19, 2026.</p><h2>Calculator inputs</h2><p>Calculations run in your browser. This site does not send calculator inputs to a server, store them in cookies or browser storage, or require an account. Values are not intentionally saved after you leave a page.</p><h2>Hosting and external links</h2><p>GitHub Pages hosts this website. Requests to the host necessarily include technical connection data, such as an IP address and requested URL. See <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub’s privacy statement</a>. Following an external link takes you to a service with its own privacy practices.</p><h2>Advertising and analytics</h2><p>Google AdSense and Google Analytics are not currently enabled. No advertising or analytics cookies are intentionally set by this website. If these services are activated, this policy will first be updated to identify the providers, data uses, cookies, user choices and any applicable consent mechanism. Enabling future services may allow Google and its partners to process data for advertising or measurement.</p><h2>Contact and changes</h2><p>Reports made through GitHub are handled by GitHub and may be public. Do not post private financial or health information. Visit <a href="contact.html">Contact</a> for the reporting route. This policy will be revised when site practices change.</p>`],
 'terms':['Terms of Use','Understand the scope and limitations of Calculator World’s free mathematical tools.',`<p>Last updated: September 19, 2026.</p><h2>Informational tools</h2><p>Calculator World provides mathematical estimates based on your inputs and the assumptions described on each page. It does not provide personalized financial, medical, legal, tax or engineering advice.</p><h2>Your inputs and decisions</h2><p>You are responsible for choosing suitable inputs, checking that the model fits your question and independently verifying results before important decisions. Display rounding and real-world conventions can cause differences from invoices, lender statements or measurements.</p><h2>Availability and corrections</h2><p>The website is provided as available. Accuracy and uninterrupted availability are not guaranteed. Tools may change as errors are corrected or methods are improved. Report calculation problems through <a href="contact.html">Contact</a>; avoid sending private information.</p>`],
 'contact':['Contact & Report a Problem','Report a calculation error or suggest a useful tool through the Calculator World project repository.',`<p>Found a calculation that looks wrong, an inaccessible control or a broken link? Use the project’s <a href="https://github.com/Colonel94/calculator-world/issues">GitHub issue tracker</a>. Reading reports is public; submitting a report requires a GitHub account.</p><h2>Make an error report useful</h2><p>Include the calculator page, non-sensitive example inputs, the result you received and the result you expected. A formula or reliable reference helps reproduce a calculation problem.</p><h2>Keep personal information private</h2><p>GitHub issues are public. Use invented example amounts and dates instead of account details, medical records or other identifying information. This site does not offer individual advice or customer support, and a response is not guaranteed.</p>`]
};
for(const [slug,[title,description,body]] of Object.entries(info))await write(slug+'.html',page(slug+'.html',title,description,`<div class="reading"><h1>${title}</h1>${body}</div>`));
await write('404.html',page('404.html','Page Not Found','Find a working calculator from the Calculator World directory.',`<h1>That page could not be found.</h1><p>Visit the <a href="${config.base}">calculator directory</a> to find the tool you need.</p>`,{noindex:true}));
const paths=['',...Object.keys(categories).map(categoryPath),...calculators.map(c=>c.id+'.html'),...Object.keys(info).map(k=>k+'.html')];
await write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${paths.map(p=>`<url><loc>${url(p)}</loc></url>`).join('\n')}\n</urlset>`);
await write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${url('sitemap.xml')}\n# For project Pages, crawlers read /robots.txt at the origin, not this subdirectory copy.`);
await write('.nojekyll','');
await write('assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="6" fill="#176451"/><path d="M8 12h16M8 20h16" stroke="white" stroke-width="3"/></svg>');
await write('docs/generated-manifest.json',JSON.stringify({calculators:calculators.length,indexable:paths,legacyCount:25},null,2));
console.log(`Built ${calculators.length} calculators, ${Object.keys(categories).length} category hubs and ${paths.length} indexable pages.`);
